config/routes.rb
Rails.application.routes.draw do
  
  # 社員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  # 管理者用
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # 社員用

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/index' => 'homes#index', as: 'index'
    get '/searchs' => 'searchs#search'
    resources :favorites, only: [:index]
    resources :comments, only: [:index]
    resources :products, only: [:new,:create,:show,:edit,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
      member do
        get 'confirm'
        patch 'take_over'
        get 'reference'
        patch 'update_status'
      end
    end
    
    get '/new_products' => 'products#new_index'
    get '/used_products' => 'products#used_index'
    resource :tags, only: [:show]
    get 'users' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/products_index' => 'users#products_index'
    resources :inquiries, only: [:new]
    post 'inquiry/completion' => 'inquiries#completion'
    resources :notifications, only: [:index, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end
  
  # 管理者用

  namespace :admin do
    get '/' => 'homes#top'
    resources :inquiries, only: [:update]
    resources :departments, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :products, only: [:index,:show,:edit,:update,:destroy] do
      collection do
        get 'search' => 'products#search'
      end
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index,:edit,:create,:update, :destroy]
    resources :users, only: [:index,:show,:edit,:update] do
        collection do
      get 'search' => 'users#search'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
  has_many :scores

  validates :name, presence: true
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @department = Department.new
    @departments = Department.all
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:notice] = "データの追加に成功しました"
      redirect_to admin_departments_path
    else
      @departments = Department.all
      render :index
    end
  end

  def show
    @department = Department.find(params[:id])
    @users = @department.users.page(params[:page])
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if  @department.update(department_params)
      flash[:notice] = "データの更新に成功しました"
      redirect_to admin_departments_path
    else
      render :edit
    end
  end

  def destroy
    department = Department.find(params[:id])
    department.destroy
    flash[:notice] = "データを削除しました"
    redirect_to admin_tags_path
  end

  private

  def department_params
  params.require(:department).permit(:name)
  end

end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/views/admin/departments/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">部門編集</h5>
  </div>
    </div>
  <div class="row ml-1">
    <%= render 'layouts/error_messages', obj: @department %>

  <div class="row">
    <%= form_with model: [:admin,@department] do |f| %>
      <div class="form mr-5">
        <%= f.text_field :name %>
        <%= f.submit '変更を保存' %>
      </div>
    <% end %>
    <div>
      <%= link_to "削除", admin_tag_path, method: :delete %>
    </div>
    
    <div class="ml-3">
      <%= link_to "戻る", admin_departments_path %>
    </div>
  </div>
</div>

app/views/admin/departments/index.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">部門一覧・追加</h5>
  </div>
  <div class="row ml-1">
    <%= render 'layouts/error_messages', obj: @department %>
  </div>
  
  <div>
    <%= form_with model: [:admin, @department] do |f| %>
      <%= f.label :name, "部門名", class:"mr-3" %>
        <%= f.text_field :name, class:"mr-3" %>
        <%= f.submit '追加' %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <table class="table my-5">
        <thead class="thead-light">
          <tr>
            <th><b></b></th>
            <th></th>
          </tr>
          </thead>
          <tbody>
            <% @departments.each do |department| %>
              <tr>
                <td><%= link_to department.name, admin_department_path(department) %></td>
                <td><%= link_to "編集", edit_admin_department_path(department) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>  
</div>

app/views/admin/departments/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">社員一覧(<%= @department.name %>)</h5>
    
    <table class="table table-sm">
      <thead>
        <tr>
          <th>社員番号</th>
          <th>名前</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= link_to user.name,admin_user_path(user) %></td>
            <td><%= user.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <div class="text-center mx-auto">
      <hr>
      <%= paginate @users %>
    </div>
  </div>  
</div>