config/routes.rb
Rails.application.routes.draw do
  
  # 社員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  # 管理者用
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # 社員用

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/index' => 'homes#index', as: 'index'
    get '/searchs' => 'searchs#search'
    resources :favorites, only: [:index]
    resources :comments, only: [:index]
    resources :products, only: [:new,:create,:show,:edit,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
      member do
        get 'confirm'
        patch 'take_over'
        get 'reference'
        patch 'update_status'
      end
    end
    
    get '/new_products' => 'products#new_index'
    get '/used_products' => 'products#used_index'
    resource :tags, only: [:show]
    get 'users' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/products_index' => 'users#products_index'
    resources :inquiries, only: [:new]
    post 'inquiry/completion' => 'inquiries#completion'
    resources :notifications, only: [:index, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end
  
  # 管理者用

  namespace :admin do
    get '/' => 'homes#top'
    resources :inquiries, only: [:update]
    resources :departments, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :products, only: [:index,:show,:edit,:update,:destroy] do
      collection do
        get 'search' => 'products#search'
      end
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index,:edit,:create,:update, :destroy]
    resources :users, only: [:index,:show,:edit,:update] do
        collection do
      get 'search' => 'users#search'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  belongs_to :giver, class_name: 'User', foreign_key: :giver_id
  belongs_to :taker, class_name: 'User', foreign_key: :taker_id, optional: true
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :favorites, dependent: :destroy
  has_many :comments
  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  validates :name,  presence: true
  validates :price,  presence: true
  validates :count,  presence: true

  def status
    if is_used == true
      "開封済"
    else
      "未開封"
    end
  end

  def is_closed_text
    if is_closed == true
      "CLOSED"
    else
      "OPEN"
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def create_notification_comment(current_user)
    notification = current_user.active_notifications.new(
      product_id: id,
      visited_id: giver_id,
      action: 'comment'
      )
    if notification.valid?
    notification.save
    end

    #本人からのコメント通知は削除する
    if notification.visitor_id == notification.visited_id
    notification.destroy
    end
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @products = Product.page(params[:page]).per(20)
    @q = Product.ransack(params[:q])
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.page(params[:page])
    @tags = @product.tags
  end

  def update
    product = Product.find(params[:id])
    product.update(is_closed: !product.is_closed)
    redirect_to admin_product_path(product), notice: "情報の更新に成功しました。"
  end

  def search
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page])
  end
  
  private

  def product_params
    params.require(:product).permit(:giver_id, :name, :detail_page, :information, :price, :count,
    :is_closed, :is_used, :taker_id, tag_ids: [])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_index.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th style="width: 5%;" >ID</th>
      <th style="width: 15%;">投稿日</th>
      <th style="width: 20%;">投稿者</th>
      <th style="width: 50%;">製品名・型式</th>
      <th style="width: 10%;"></th>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.created_at.strftime('%Y/%-m/%-d %H:%M') %></td>
        <td><%= link_to product.giver.name, admin_user_path(product.giver_id) %>(<%= product.giver.department.name %>)</td>
        <td class="d-inline-block text-truncate", style="width: 560px;"><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= product.is_closed_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
   <%= f.search_field :name_cont, placeholder: '検索ワード' %>
   <%= f.submit '検索' %>
<% end %>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">出品備品一覧</h5>
    <div class="ml-auto"><%= render 'admin/products/search', q: @q, url: search_admin_products_path %></div>
    <%= render "admin/products/index", products: @products %>
    <div class="text-center mx-auto">
      <hr>
      <%= paginate @products %>
    </div>
  </div>  
</div>

app/views/admin/products/search.html.erb
<div class="container">
  <div class="row">
    <% if @products.present? %>
      <h5 class="font-weight-bold ml-3">検索結果<%= @products.count %>件</h5>
      <div class="ml-auto"><%= render 'admin/products/search', q: @q, url: search_admin_products_path %></div>
        <%= render "admin/products/index", products: @products %>
        <div class="text-center mx-auto">
        <hr>
        <%= paginate @products %>
      </div>
    <% else %>
      <h5 class="font-weight-bold ml-3">検索結果はありません</h5>
      <div class="ml-auto"><%= render 'admin/products/search', q: @q, url: search_admin_products_path %></div>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="row">
      <table class="table table-borderless">
        <tr>
          <th class="pb-0"><%= @product.created_at.strftime('%Y/%-m/%-d  %H:%M') %></th>
          <th class="pb-0">ID:<%= @product.id %></th>
          <th class="pb-0"><%= @product.giver.name %></th>
          <th class="pb-0", style="width: 350px;"><%= @product.name %></th>
          <th class="pb-0"><%= @product.status %></th>
          <th class="pb-0">
              <% if @product.taker_id.present? %>
                <%= @product.taker.name %>(<%= @product.taker.department.name %>)さんが引き取り済み(<%= @product.updated_at.strftime('%Y/%-m/%-d') %>)
              <% elsif @product.is_closed? %>
                <%= link_to "公開にする", admin_product_path,method: :patch %>
              <% else %>
                <%= link_to "非公開にする", admin_product_path, method: :patch %>
              <% end %>
          </th>
        </tr>
      </table>
      
      <table class="table table-borderless">
        <tr>
          <th class="py-0">個数：<%= @product.count %></th>
          <th class="py-0">価格：<%= @product.price.to_s(:delimited) %>円</th>
          <% if @product.detail_page.present? %>
            <th class="py-0">類似品ページ：<%= link_to @product.detail_page, @product.detail_page, target: :_blank, rel: "noopener noreferrer" %></th>
          <% end %>
          <th style="width: 200px;">
            <% if @tags.present? %>
              <% @tags.each do |tag| %>
                <i class="fas fa-tag pl-3"></i><%= tag.name %>
              <% end %>
            <% end %>
          </th>
        </tr>
      </table>

      <div class="pt-0 pb-2 ml-2">備考：<%= @product.information %></div>
    </div>
    
    <div class="row ml-1", style="width: 100%;">
      <h4>コメント</h4>
      <table class="table table-sm">
        <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.created_at.strftime('%Y/%-m/%-d  %H:%M') %></td>
          <td><%= comment.user.name %>(<%= comment.user.department.name %>)</td>
          <td style="width: 60%;"><%= comment.body %></td>
          <td><%= link_to"削除", admin_product_comment_path(comment.product, comment), method: :delete %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
  
  <div class="row">
    <div class="text-center mx-auto">
      <hr>
      <%= paginate @comments %>
    </div>
  </div>
</div>