config/routes.rb
Rails.application.routes.draw do
  
  # 社員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  # 管理者用
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # 社員用

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/index' => 'homes#index', as: 'index'
    get '/searchs' => 'searchs#search'
    resources :favorites, only: [:index]
    resources :comments, only: [:index]
    resources :products, only: [:new,:create,:show,:edit,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
      member do
        get 'confirm'
        patch 'take_over'
        get 'reference'
        patch 'update_status'
      end
    end
    
    get '/new_products' => 'products#new_index'
    get '/used_products' => 'products#used_index'
    resource :tags, only: [:show]
    get 'users' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/products_index' => 'users#products_index'
    resources :inquiries, only: [:new]
    post 'inquiry/completion' => 'inquiries#completion'
    resources :notifications, only: [:index, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end
  
  # 管理者用

  namespace :admin do
    get '/' => 'homes#top'
    resources :inquiries, only: [:update]
    resources :departments, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :products, only: [:index,:show,:edit,:update,:destroy] do
      collection do
        get 'search' => 'products#search'
      end
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index,:edit,:create,:update, :destroy]
    resources :users, only: [:index,:show,:edit,:update] do
        collection do
      get 'search' => 'users#search'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:employee_number]
         validates :name, presence: true
         validates :employee_number, presence: true, length: { minimum: 5 }

  belongs_to :department
  has_many :scores
  has_many :products, foreign_key: :giver_id
  has_many :products, foreign_key: :taker_id
  has_many :favorites, dependent: :destroy
  has_many :comments
  has_many :read_counts, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :employee_number, uniqueness: true

  def active_for_authentication?
    super && (is_deleted == false)
  end


 # No use email
  def email_required?
    false
  end
  def email_changed?
    false
  end
  def will_save_change_to_email?
    false
  end

  def status
    if is_deleted == false
      "有効"
    else
      "無効"
    end
  end

  def self.ransackable_associations(auth_object = nil)
    ["department"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["employee_number", "name"]
  end


  GUEST_USER_EMPLOYEE_NUMBER = "123456"

  def self.guest
    find_or_create_by!(employee_number: GUEST_USER_EMPLOYEE_NUMBER) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.department = Department.first
      user.name = "guestuser"
    end
  end

  def guest_user?
    employee_number == GUEST_USER_EMPLOYEE_NUMBER
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page]).per(20)
    @q = User.ransack(params[:q])
  end
  
  def show
    @user = User.find(params[:id])
    @products = Product.where(giver_id: @user).page(params[:products_page]).per(10)
    @comments = @user.comments.page(params[:comments_page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "情報の更新に成功しました。"
    else
      render "edit"
    end
  end
  
  def search
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page])
  end
  
  def user_params
    params.require(:user).permit( :name, :department_id, :employee_number, :is_deleted)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>名前</th>
      <th>所属部門</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.employee_number %></td>
        <td><%= link_to user.name,admin_user_path(user) %></td>
        <td><%= user.department.name %></td>
        <td><%= user.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
   <%= f.search_field :name_or_employee_number_cont, placeholder: '検索ワード' %>
   <%= f.submit '検索' %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">従業員情報編集画面</h5>
  </div> 
  
  <div class="row">
    <div class="col">
      <%= form_with model: @user, url: admin_user_path do |f| %>
        <div class="field">
          <%= f.label :name, '名前' %><br />
          <%= f.text_field :name, autofocus: true %>
        </div>
        
        <div class="field">
          <%= f.label :employee_number, '社員番号' %><br />
          <%= f.text_field :employee_number, autofocus: true %>
        </div>
        
        <div class="field">
          <%= f.label :department_id, '所属部署' %><br />
          <%= f.select :department_id, Department.pluck(:name, :id), { include_blank: "--選択してください--"} %>
        </div>
        
        <div class="field">
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, '有効', value: false %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, '無効', value: true %>
        </div>
        
        <div class="actions">
          <%= f.submit "保存" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h5 class="font-weight-bold ml-3">社員一覧</h5>
    <div class="ml-auto"><%= render 'admin/users/search', q: @q, url: search_admin_users_path %></div>
      <%= render "admin/users/index", users: @users %>
    <div class="text-center mx-auto">
      <hr>
      <%= paginate @users %>
    </div>
  </div>  
</div>

app/views/admin/users/search.html.erb
<div class="container">
  <div class="row">
    <% if @users.present? %>
      <h5 class="font-weight-bold ml-3">検索結果<%= @users.count %>件</h5>
      <div class="ml-auto">
        <%= render 'admin/users/search', q: @q, url: search_admin_users_path %>
      </div>
      <%= render "admin/users/index", users: @users %>
      <div class="text-center mx-auto">
        <hr>
        <%= paginate @users %>
      </div>
    <% else %>
      <h5 class="font-weight-bold ml-3">検索結果はありません</h5>
      <div class="ml-auto">
        <%= render 'admin/users/search', q: @q, url: search_admin_users_path %>
      </div>
    <% end %>
  </div>  
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <table class="table table-borderless">
      <tr>
        <th><%= @user.employee_number %></th>
        <th><%= @user.name %></th>
        <th><%= @user.department.name %></th>
        <th><%= @user.status %></th>
        <th><%= link_to '編集',edit_admin_user_path(@user) %></th>
      </tr>
    </table>
    <hr>
  </div>
  
  <div class="row">
    <div class="col-6 userpage-content">
      <h5 class="font-weight-bold ml-3">投稿履歴</h5>
      <table class="table table-sm table-borderless">
        <% @products.each do |product| %>
          <tr>
            <td><%= product.created_at.strftime('%Y/%-m/%-d') %></td>
            <td class="d-inline-block text-truncate", style="width: 130px;"><%= link_to product.name, admin_product_path(product) %></td>
            <td>閲覧：<%= product.read_counts.count %>回</td>
            <td>コメント：<%= product.comments.count %>件</td>
          </tr>
        <% end %>
      </table>
      
      <div class="row">
        <div class="text-center mx-auto">
          <hr>
        <%= paginate @products, param_name: :products_page %>
        </div>
      </div>
    </div>
    
    <div class="col-6 userpage-content">
      <h5 class="font-weight-bold ml-3">コメント履歴</h5>
      <% @comments.each do |comment| %>
        <div class="row ml-5">
          <%= comment.created_at.strftime('%Y/%-m/%-d') %></td>
          <p class="d-inline-block text-truncate ml-2", style="width: 130px;"><%= link_to comment.product.name, admin_product_path(comment.product) %></p>
          <div class="text-right">
            <%= link_to"コメント削除", admin_product_comment_path(comment.product, comment), method: :delete %>
          </div>
        </div>
        
        <div class="row ml-5">
          <p><%= comment.body %></p>
        </div>
        <hr class="m-0">
      <% end %>
      <div class="row">
        <div class="text-center mx-auto">
          <hr>
          <%= paginate @comments, param_name: :comments_page %>
        </div>
      </div>
    </div>
  </div>
</div>