config/routes.rb
Rails.application.routes.draw do
  
  # 社員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  # 管理者用
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # 社員用

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/index' => 'homes#index', as: 'index'
    get '/searchs' => 'searchs#search'
    resources :favorites, only: [:index]
    resources :comments, only: [:index]
    resources :products, only: [:new,:create,:show,:edit,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
      member do
        get 'confirm'
        patch 'take_over'
        get 'reference'
        patch 'update_status'
      end
    end
    
    get '/new_products' => 'products#new_index'
    get '/used_products' => 'products#used_index'
    resource :tags, only: [:show]
    get 'users' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/products_index' => 'users#products_index'
    resources :inquiries, only: [:new]
    post 'inquiry/completion' => 'inquiries#completion'
    resources :notifications, only: [:index, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end
  
  # 管理者用

  namespace :admin do
    get '/' => 'homes#top'
    resources :inquiries, only: [:update]
    resources :departments, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :products, only: [:index,:show,:edit,:update,:destroy] do
      collection do
        get 'search' => 'products#search'
      end
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index,:edit,:create,:update, :destroy]
    resources :users, only: [:index,:show,:edit,:update] do
        collection do
      get 'search' => 'users#search'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<div class="ml-5 mt-3 text-info">
  <p id="notice"><%= notice %></p>
</div>
<div class="ml-5 mt-3 text-danger">
  <p id="alert"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom mx-auto footer">
  <div class='container mt-3'>
  	<div class='row'>
    	<div class='mx-auto'>

    	</div>
    </div>
    <div class='row banner-container'>
    	<div class='col-4 mx-auto text-center'>
    	  <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
        <a href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>
        <!-- Rakuten Web Services Attribution Snippet TO HERE -->
    	  <a href="https://github.com/ikutanaoko/RescUse_2023" >https://github.com/ikutanaoko/RescUse_2023</a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container header-nav-box">
      <div class="logo">
        <!-- 社員ログイン時　-->
        <% if user_signed_in? %>
          <%= link_to users_path do %>
            <div class="svg_wrapper">
              <%= embedded_svg('RescUse_black_1.svg', class: 'logo_svg') %>
            </div>
          <% end %>

        <!-- 管理者ログイン時　-->
        <% elsif admin_signed_in? %>
          <%= link_to admin_path do %>
            <div class="svg_wrapper">
              <%= embedded_svg('RescUse_black_1.svg', class: 'logo_svg') %>
            </div>
          <% end %>
        
        <!-- ログイン前　-->
        <% else %>
          <%= link_to root_path do %>
            <div class="svg_wrapper">
              <%= embedded_svg('RescUse_black_1.svg', class: 'logo_svg') %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto humburger-border" id="nav">
          
          <!-- 社員ログイン時　-->
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", users_path, class: 'btn navbar-btn' %>
              <ul class="drop-menu">
                <li><%= link_to "新着通知", notifications_path, class: "drop-menu-link" %></li>
                <li><%= link_to "出品一覧", users_products_index_path, class: "drop-menu-link" %></li>
                <li><%= link_to "引取一覧", index_path, class: "drop-menu-link" %></li>
                <li><%= link_to "保存済み", favorites_path, class: "drop-menu-link" %></li>
              </ul>
            </li>
            
            <li class="nav-item">
              <div class='btn navbar-btn'>メニュー</div>
              <ul class="drop-menu">
                <li><%= link_to "新規出品", new_product_path, class: "drop-menu-link" %></li>
                <li><%= link_to "未開封一覧", new_products_path, class: "drop-menu-link" %></li>
                <li><%= link_to "開封済一覧", used_products_path, class: "drop-menu-link" %></li>
                <li><%= link_to "問い合わせ", new_inquiry_path, class: "drop-menu-link" %></li>
              </ul>
            </li>
            
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn navbar-btn' do %>ログアウト<% end %>
            </li>
            
          <!-- 管理者ログイン時　-->
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <div class='btn navbar-btn'>
                メニュー
              </div>

              <ul class="drop-menu">
                <li><%= link_to "社員一覧", admin_users_path, class: "drop-menu-link" %></li>
                <li><%= link_to "部門一覧", admin_departments_path, class: "drop-menu-link" %></li>
                <li><%= link_to "タグ一覧", admin_tags_path, class: "drop-menu-link" %></li>
                <li><%= link_to "出品備品一覧", admin_products_path, class: "drop-menu-link" %></li>
                <li><%= link_to "問い合わせ履歴", admin_path, class: "drop-menu-link" %></li>
              </ul>
            </li>
            
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'btn navbar-btn' do %>ログアウト<% end %>
            </li>
            
          <!-- ログイン前　-->
          <% else %>
            <li class="nav-item"><%= link_to "初めての方", about_path, class: 'btn navbar-btn' %></li>
            <li class="nav-item"><%= link_to "問い合わせ", new_inquiry_path, class: 'btn navbar-btn' %></li>
            <li class="nav-item"><%= link_to "ログイン", new_user_session_path , class: 'btn navbar-btn' %></li>
          <% end %>

          <div class="d-flex align-items-center">
            <% if user_signed_in? %>
               <p class="mb-0 text-dark font-weight-bold ml-auto"><%= current_user.name %> さん</p>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

<script>
  $(function() {
    $('#nav li').mouseover(function(e) {
      $('ul', this).stop().slideDown('fast');
    })
    .mouseout(function(e) {
      $('ul', this).stop().slideUp('fast');
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescUse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/6bb66a36c5.js" crossorigin="anonymous"></script>
    <%# stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  
  
  <body>
    <%= render 'layouts/header' %>
    
    <main>
      <%= render 'layouts/flash_message' %>
      <div class="container mb-5 pb-5">
        <%= yield %>
      </div>
    </main>
    
    <%= render 'layouts/footer' %>
  </body>
</html>